# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'YourDockerRegistryServiceConnection'
    repository: 'your-docker-repo-name'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest
      $(Build.BuildId)